stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building the project..."
    - mvn clean compile

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - mvn test
